UPLOAD_PATH = 'app/assets/images'
SITE_URL = 'http:/anti-pms.com'
SITE_NAME = 'ANTI-PMS.COM'
WAIT_CONFIRM ='wait_confirm'
CONFIRMED = 'confirmed'
DEMO_MALE = 2
DEMO_FEMALE = 3
MAX_ID_DEMO = 5
# 0-ru, -1-en
LANGUAGE = 0
NOTHING = 0 #nothing
NEW = 1 #new
NEW_SAVED = 2 #new saved
RETURNED = 9 #returned
EDIT = 10 #edit
EDITED = 11 #edited
EDITED_SAVED = 12 #edited saved
BLOCK = 20 #block
BLOCKED = 21 #blocked
BLOCKED_SAVED = 22 #blocked saved
DELETE = 30 #delete
DELETED = 31 #deleted
DELETED_SAVED = 32 #deleted saved
NOTIFY_MAIL_NOT_SENT = 41
NOTIFY_MAIL_SENT = 42
TRACE_MAIL_NOT_SENT = 43
TRACE_MAIL_SENT = 44
BAN_MAIL_SENT = 45
BAN_MAIL_NOT_SENT = 46
ADMIN = 101 #account admin
PAID = 101 #account paid

BIRTHDAY = 1
PMS = 2
MENSTRUAL = 3
OVULATE = 4
SEXY = 5
EVIL = 6
